name: Build and Test

on: [push, pull_request]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: ./frontend
        run: bun install

      - name: Check formatting
        working-directory: ./frontend
        run: bun run format

      - name: Run linter
        working-directory: ./frontend
        run: bun run lint

      - name: Build frontend
        working-directory: ./frontend
        run: bun run build

  backend-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Check formatting
        working-directory: ./backend
        run: ./gradlew spotlessCheck

      - name: Build and Test backend
        working-directory: ./backend
        run: ./gradlew build
